### ISSUE TITLE
Removing dotenv dependency

### ISSUE THREAD

**Issue by AndreiSva** [Bulldog-Computer-Club/inu#1]
It's not only completely unnecessary but it makes the bot not function correctly on certain systems such as OpenBSD.

@jo3-l @Crabo-7498

**Comment by jo3-l** [comment]
It's necessary for loading environment values from the `.env` file when running via Docker.

**Comment by jo3-l** [comment]
...actually never mind, ignore my previous comment. Still, though, we can make it an optional dependency instead of removing it entirely.

**Comment by AndreiSva** [comment]
I've also discovered that there's actually a port of dotenv that works on OpenBSD so that fixes the issue partly. In the unlikely situation someone is looking at this trying to get it to work on OpenBSD the package name is py3-dotenv

**Comment by AndreiSva** [comment]
And actually it appears I've been trying to install the whole dependency wrong all along, guess this isn't an issue anymore! Whoops!
